export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";

export const FETCH_BOARD_REQUEST = "FETCH_BOARD_REQUEST";
export const BOARD_FETCHED = "BOARD_FETCHED";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
